export const actionsTypes = {
  GET_SINGLE_USER_PHOTOS: "GET_SINGLE_USER_PHOTOS",
  GET_RANDOM_PHOTO: "GET_RANDOM_PHOTO",
  GET_PHOTOS: "GET_PHOTOS",
  GET_COLLECTIONS: "GET_COLLECTIONS",
  GET_USERS: "GET_USERS",
  HANDLE_SEARCH_INPUT_VALUE_CHANGE: "HANDLE_SEARCH_INPUT_VALUE_CHANGE",
  GET_SINGLE_COLLECTION_PHOTOS: "GET_SINGLE_COLLECTION_PHOTOS",
  SET_ACTIVE_SEARCH_TYPE: "SET_ACTIVE_SEARCH_TYPE",
};
