export const actionsTypes = {
  setPhotosList: "SET_PHOTOS_LIST",
  GET_SINGLE_USER_PHOTOS: "GET_SINGLE_USER_PHOTOS",
  GET_RANDOM_PHOTO: "GET_RANDOM_PHOTO",
  GET_PHOTOS: "GET_PHOTOS",
  GET_COLLECTIONS: "GET_COLLECTIONS",
  GET_USERS: "GET_USERS",
};
